In [1]:
import pandas as pd 
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent
CSV_DIR = BASE_DIR / "csv"

In [3]:
deliveries = pd.read_csv(CSV_DIR / "deliveries.csv")
orders = pd.read_csv(CSV_DIR / "orders.csv")
restaurants = pd.read_csv(CSV_DIR / "restaurants.csv")
riders = pd.read_csv(CSV_DIR / "riders.csv")
order_events = pd.read_csv(CSV_DIR / "order_events.csv")

In [4]:
deliveries

,delivery_id,order_id,rider_id,assigned_at,picked_up_at,delivered_at
0,1,1,3,2026-01-17 12:35:24,2026-01-17 13:02:24,2026-01-17 13:23:24
1,2,2,33,2026-01-05 12:28:54,2026-01-05 12:54:54,2026-01-05 13:16:54
2,3,3,69,2026-01-09 23:45:54,2026-01-10 00:15:54,2026-01-10 00:31:54
3,4,4,74,2026-01-24 19:58:54,2026-01-24 20:16:54,2026-01-24 20:30:54
4,5,5,39,2026-01-31 13:25:26,2026-01-31 13:56:26,2026-01-31 14:33:26
...,...,...,...,...,...,...
9288,9289,9996,7,2026-01-19 12:46:21,2026-01-19 13:19:21,2026-01-19 13:34:21
9289,9290,9997,6,2026-01-06 13:36:13,2026-01-06 14:14:13,2026-01-06 14:42:13
9290,9291,9998,60,2026-01-06 18:44:44,2026-01-06 19:08:44,2026-01-06 19:26:44
9291,9292,9999,72,2026-01-24 23:18:32,2026-01-24 23:40:32,2026-01-24 23:59:32
9292,9293,10000,53,2026-01-18 07:20:16,2026-01-18 07:41:16,2026-01-18 08:08:16

In [5]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9293 entries, 0 to 9292
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   delivery_id   9293 non-null   int64
 1   order_id      9293 non-null   int64
 2   rider_id      9293 non-null   int64
 3   assigned_at   9293 non-null   object
 4   picked_up_at  9293 non-null   object
 5   delivered_at  9293 non-null   object
dtypes: int64(3), object(3)
memory usage: 435.7+ KB

In [6]:
deliveries.duplicated().sum()

np.int64(0)

In [7]:
date_cols = [
    "assigned_at",
    "picked_up_at",
    "delivered_at"
]

for col in date_cols:
    deliveries[col] = pd.to_datetime(deliveries[col])

In [8]:
deliveries["hour"] = deliveries["assigned_at"].dt.hour
deliveries["day"] = deliveries["assigned_at"].dt.day_name()
deliveries["month"] = deliveries["assigned_at"].dt.month

In [9]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9293 entries, 0 to 9292
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   delivery_id   9293 non-null   int64
 1   order_id      9293 non-null   int64
 2   rider_id      9293 non-null   int64
 3   assigned_at   9293 non-null   datetime64[ns]
 4   picked_up_at  9293 non-null   datetime64[ns]
 5   delivered_at  9293 non-null   datetime64[ns]
 6   hour          9293 non-null   int32
 7   day           9293 non-null   object
 8   month         9293 non-null   int32
dtypes: datetime64[ns](3), int32(2), int64(3), object(1)
memory usage: 580.9+ KB

In [10]:
deliveries.head()

,delivery_id,order_id,rider_id,assigned_at,picked_up_at,delivered_at,hour,day,month
0,1,1,3,2026-01-17 12:35:24,2026-01-17 13:02:24,2026-01-17 13:23:24,12,Saturday,1
1,2,2,33,2026-01-05 12:28:54,2026-01-05 12:54:54,2026-01-05 13:16:54,12,Monday,1
2,3,3,69,2026-01-09 23:45:54,2026-01-10 00:15:54,2026-01-10 00:31:54,23,Friday,1
3,4,4,74,2026-01-24 19:58:54,2026-01-24 20:16:54,2026-01-24 20:30:54,19,Saturday,1
4,5,5,39,2026-01-31 13:25:26,2026-01-31 13:56:26,2026-01-31 14:33:26,13,Saturday,1

In [11]:
deliveries["prep_minutes"] = (
    deliveries["picked_up_at"] - deliveries["assigned_at"]
).dt.total_seconds() / 60

deliveries["delivery_minutes"] = (
    deliveries["delivered_at"] - deliveries["picked_up_at"]
).dt.total_seconds() / 60

deliveries["total_minutes"] = (
    deliveries["delivered_at"] - deliveries["assigned_at"]
).dt.total_seconds() / 60

In [12]:
deliveries.head()

,delivery_id,order_id,rider_id,assigned_at,picked_up_at,delivered_at,hour,day,month,prep_minutes,delivery_minutes,total_minutes
0,1,1,3,2026-01-17 12:35:24,2026-01-17 13:02:24,2026-01-17 13:23:24,12,Saturday,1,27.0,21.0,48.0
1,2,2,33,2026-01-05 12:28:54,2026-01-05 12:54:54,2026-01-05 13:16:54,12,Monday,1,26.0,22.0,48.0
2,3,3,69,2026-01-09 23:45:54,2026-01-10 00:15:54,2026-01-10 00:31:54,23,Friday,1,30.0,16.0,46.0
3,4,4,74,2026-01-24 19:58:54,2026-01-24 20:16:54,2026-01-24 20:30:54,19,Saturday,1,18.0,14.0,32.0
4,5,5,39,2026-01-31 13:25:26,2026-01-31 13:56:26,2026-01-31 14:33:26,13,Saturday,1,31.0,37.0,68.0

In [13]:
(deliveries["prep_minutes"] + deliveries["delivery_minutes"] 
 == deliveries["total_minutes"]).all()

np.True_

In [14]:
order_events

       event_id  order_id event_name      event_timestamp
0             1         1    CREATED  2026-01-17 12:31:24
1             2         1   ACCEPTED  2026-01-17 12:35:24
2             3         1  PREPARING  2026-01-17 12:37:24
3             4         1      READY  2026-01-17 12:54:24
4             5         1  PICKED_UP  2026-01-17 13:02:24
...         ...       ...        ...                  ...
58981     58982     10000   ACCEPTED  2026-01-18 07:20:16
58982     58983     10000  PREPARING  2026-01-18 07:23:16
58983     58984     10000      READY  2026-01-18 07:34:16
58984     58985     10000  PICKED_UP  2026-01-18 07:41:16
58985     58986     10000  DELIVERED  2026-01-18 08:08:16

[58986 rows x 4 columns]

In [15]:
order_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58986 entries, 0 to 58985
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         58986 non-null  int64
 1   order_id         58986 non-null  int64
 2   event_name       58986 non-null  object
 3   event_timestamp  58986 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.8+ MB

In [16]:
order_date = ['event_timestamp']
for col in order_date:
    order_events[col] = pd.to_datetime(order_events[col])

In [17]:
order_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58986 entries, 0 to 58985
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         58986 non-null  int64
 1   order_id         58986 non-null  int64
 2   event_name       58986 non-null  object
 3   event_timestamp  58986 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 1.8+ MB

In [18]:
order_events.duplicated().sum()

np.int64(0)

In [19]:
order_events['event_name'].head()

0      CREATED
1     ACCEPTED
2    PREPARING
3        READY
4    PICKED_UP
Name: event_name, dtype: object

In [20]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 10000 non-null  int64
 1   created_at               10000 non-null  object
 2   order_value              10000 non-null  float64
 3   items_count              10000 non-null  int64
 4   estimated_prep_time      10000 non-null  int64
 5   estimated_delivery_time  10000 non-null  int64
 6   customer_lat             10000 non-null  float64
 7   customer_lon             10000 non-null  float64
 8   order_status             10000 non-null  object
 9   restaurant_id            10000 non-null  int64
 10  weather_level            10000 non-null  object
 11  traffic_level            10000 non-null  object
dtypes: float64(3), int64(5), object(4)
memory usage: 937.6+ KB

In [21]:
orders.head()

,order_id,created_at,order_value,items_count,estimated_prep_time,estimated_delivery_time,customer_lat,customer_lon,order_status,restaurant_id,weather_level,traffic_level
0,1,2026-01-17 12:31:24,80.13,6,17,21,43.275816,-2.914033,DELIVERED,39,RAIN,MEDIUM
1,2,2026-01-05 12:24:54,60.95,6,20,22,43.274594,-2.953613,DELIVERED,26,CLEAR,MEDIUM
2,3,2026-01-09 23:42:54,60.08,4,22,16,43.229625,-2.950303,DELIVERED,48,CLEAR,MEDIUM
3,4,2026-01-24 19:54:54,70.73,5,14,14,43.247773,-2.899567,DELIVERED,1,CLEAR,LOW
4,5,2026-01-31 13:21:26,34.68,2,24,37,43.279074,-2.965174,DELIVERED,10,RAIN,HIGH

In [22]:
orders_date = ['created_at']
for col in orders_date:
    orders[col] = pd.to_datetime(orders[col])

In [23]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 10000 non-null  int64
 1   created_at               10000 non-null  datetime64[ns]
 2   order_value              10000 non-null  float64
 3   items_count              10000 non-null  int64
 4   estimated_prep_time      10000 non-null  int64
 5   estimated_delivery_time  10000 non-null  int64
 6   customer_lat             10000 non-null  float64
 7   customer_lon             10000 non-null  float64
 8   order_status             10000 non-null  object
 9   restaurant_id            10000 non-null  int64
 10  weather_level            10000 non-null  object
 11  traffic_level            10000 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 937.6+ KB

In [24]:
orders['order_status'].value_counts()

order_status
DELIVERED    9293
CANCELLED     707
Name: count, dtype: int64

In [25]:
orders['weather_level'].value_counts()

weather_level
CLEAR    7061
RAIN     1952
WIND      987
Name: count, dtype: int64

In [26]:
orders['traffic_level'].value_counts()

traffic_level
MEDIUM    3484
HIGH      3457
LOW       3059
Name: count, dtype: int64

In [27]:
restaurants.head()

,restaurant_id,restaurant_name,cuisine_category,base_prep_time,capacity,restaurant_zone,restaurant_lat,restaurant_lon
0,1,ASIAN_PLACE_1,ASIAN,16,10,SOUTH,43.224489,-2.974651
1,2,ITALIAN_PLACE_2,ITALIAN,25,33,WEST,43.208694,-2.943589
2,3,ITALIAN_PLACE_3,ITALIAN,16,16,NORTH,43.250536,-2.987081
3,4,BURGER_PLACE_4,BURGER,18,23,NORTH,43.244921,-2.959399
4,5,ITALIAN_PLACE_5,ITALIAN,17,32,EAST,43.234025,-2.972897

In [28]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   restaurant_id     50 non-null     int64
 1   restaurant_name   50 non-null     object
 2   cuisine_category  50 non-null     object
 3   base_prep_time    50 non-null     int64
 4   capacity          50 non-null     int64
 5   restaurant_zone   50 non-null     object
 6   restaurant_lat    50 non-null     float64
 7   restaurant_lon    50 non-null     float64
dtypes: float64(2), int64(3), object(3)
memory usage: 3.3+ KB

In [29]:
restaurants['restaurant_name'].duplicated().sum()

np.int64(0)

In [30]:
restaurants['restaurant_name'].value_counts()

restaurant_name
ASIAN_PLACE_1       1
ITALIAN_PLACE_2     1
ITALIAN_PLACE_3     1
BURGER_PLACE_4      1
ITALIAN_PLACE_5     1
SUSHI_PLACE_6       1
KEBAB_PLACE_7       1
HEALTHY_PLACE_8     1
SUSHI_PLACE_9       1
SUSHI_PLACE_10      1
HEALTHY_PLACE_11    1
ASIAN_PLACE_12      1
ASIAN_PLACE_13      1
ASIAN_PLACE_14      1
BURGER_PLACE_15     1
KEBAB_PLACE_16      1
HEALTHY_PLACE_17    1
SUSHI_PLACE_18      1
BURGER_PLACE_19     1
BURGER_PLACE_20     1
KEBAB_PLACE_21      1
ITALIAN_PLACE_22    1
SUSHI_PLACE_23      1
ITALIAN_PLACE_24    1
ASIAN_PLACE_25      1
BURGER_PLACE_26     1
HEALTHY_PLACE_27    1
SUSHI_PLACE_28      1
ITALIAN_PLACE_29    1
BURGER_PLACE_30     1
KEBAB_PLACE_31      1
ASIAN_PLACE_32      1
SUSHI_PLACE_33      1
ITALIAN_PLACE_34    1
ITALIAN_PLACE_35    1
SUSHI_PLACE_36      1
KEBAB_PLACE_37      1
HEALTHY_PLACE_38    1
HEALTHY_PLACE_39    1
ITALIAN_PLACE_40    1
BURGER_PLACE_41     1
HEALTHY_PLACE_42    1
KEBAB_PLACE_43      1
BURGER_PLACE_44     1
ITALIAN_PLACE_45    1
HEALTHY_PLACE_46    1
BURGER_PLACE_47     1
ASIAN_PLACE_48      1
KEBAB_PLACE_49      1
KEBAB_PLACE_50      1
Name: count, dtype: int64

In [31]:
restaurants['cuisine_category'].value_counts()

cuisine_category
ITALIAN    10
BURGER      9
KEBAB       8
SUSHI       8
HEALTHY     8
ASIAN       7
Name: count, dtype: int64

In [32]:
restaurants['restaurant_zone'].value_counts()

restaurant_zone
CENTER    14
WEST      10
SOUTH      9
NORTH      9
EAST       8
Name: count, dtype: int64

In [33]:
riders.head()

   rider_id rider_name home_zone vehicle_type  max_orders_per_hour
0         1    RIDER_1      WEST         BIKE                    2
1         2    RIDER_2      WEST         BIKE                    5
2         3    RIDER_3      WEST    MOTORBIKE                    4
3         4    RIDER_4     NORTH    MOTORBIKE                    3
4         5    RIDER_5     SOUTH    MOTORBIKE                    3

In [34]:
riders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rider_id             120 non-null    int64
 1   rider_name           120 non-null    object
 2   home_zone            120 non-null    object
 3   vehicle_type         120 non-null    object
 4   max_orders_per_hour  120 non-null    int64
dtypes: int64(2), object(3)
memory usage: 4.8+ KB